name: "Gradle Build Test"

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"

      - name: "Setup JDK 8"
        uses: "actions/setup-java@v2"
        with:
          java-version: "8"
          distribution: "temurin"
          architecture: "x64"

      - name: "Build with Gradle"
        run: "./gradlew clean build"
